_common/lib: !include "../hpack.yaml"
<<: *defaults

name: hive-client

dependencies:
  - base
  - react-flux

library:
  source-dirs:  src

executable:
  source-dirs:  exe
  main:         Main.hs
  dependencies:
    - hive-client
