name: hive
version: 0.0.1
author: Brandon Chinn

ghc-options: -Wall -Werror

dependencies:
  - base
  - containers
  - jsaddle
  - reflex-dom-core

library:
  source-dirs:  src

executables:
  # https://github.com/commercialhaskell/stack/issues/3918
  hive-server:
    source-dirs:  exe
    main:         Main.hs
    dependencies:
      - hive
      - jsaddle-warp
