version: 2

aliases:
  # build environment
  - &docker-linux
    docker:
      - image: centos:7
    working_directory: /root/src

  # system dependencies
  - &install-stack
    run:
      name: Install stack
      command: |
        curl -sSL https://get.haskellstack.org/ | sh
        stack --version

  # cache
  - &build-cache-key
    run:
      name: Build cache key
      command: |
        FILES=(
          stack.yaml
          stack-ghcjs.yaml
          lib/package.yaml
          server/package.yaml
          client/package.yaml
          scripts/install-system-deps.sh
          scripts/install-stack-deps.sh
        )
        cat "${FILES[@]}" > cache-key.txt
  - &cache-key
    v0-{{ checksum "cache-key.txt" }}
  - &install-system-deps
    run:
      name: Build system dependencies
      command: scripts/install-system-deps.sh
  - &install-stack-deps
    run:
      name: Build external dependencies
      command: scripts/install-stack-deps.sh

  # build steps
  - &run-build
    run:
      name: Build package
      command: ./build.sh --test --no-run-tests

  # test steps
  - &run-hlint
    run:
      name: Run hlint
      command: scripts/hlint.sh
  - &run-stylish-haskell
    run:
      name: Run stylish-haskell
      command: scripts/stylish-haskell.sh

jobs:
  prebuild:
    <<: *docker-linux
    steps:
      - checkout
      - *build-cache-key
      - persist_to_workspace:
          root: .
          paths:
            - cache-key.txt

  build:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *install-system-deps
      - *install-stack-deps
      - save_cache:
          key: *cache-key
          paths:
            - ~/.stack
      - *run-build
      - persist_to_workspace:
          root: .
          paths:
              - .stack-work

  hlint:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-hlint

  stylish-haskell:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-stylish-haskell

workflows:
  version: 2

  build_and_test:
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild
      - hlint:
          requires:
            - build
      - stylish-haskell:
          requires:
            - build
