version: 2

aliases:
  # build environment
  - &docker-linux
    docker:
      - image: centos:7
    working_directory: /root/src

  # caches
  - &build-ghc-cache-key
    run:
      name: Build cache key for ghc
      command: |
        FILES=(
          stack.yaml
          package.yaml
          scripts/install-system-deps.sh
          scripts/install-stack-deps.sh
        )
        cat "${FILES[@]}" > ghc-cache-key.txt
  - &build-ghcjs-cache-key
    run:
      name: Build cache key for ghcjs
      command: |
        FILES=(
          stack.yaml
          ghcjs/stack.yaml
          package.yaml
          scripts/install-system-deps.sh
          scripts/install-stack-deps.sh
        )
        cat "${FILES[@]}" > ghcjs-cache-key.txt
  - &ghc-cache-key
    v0-{{ checksum "ghc-cache-key.txt" }}
  - &ghcjs-cache-key
    v0-{{ checksum "ghcjs-cache-key.txt" }}

  # dependencies
  - &install-system-deps
    run:
      name: Build system dependencies
      command: scripts/install-system-deps.sh
  - &install-stack-deps
    run:
      name: Build stack dependencies
      command: scripts/install-stack-deps.sh
      no_output_timeout: 30m

  # build steps
  - &run-build-ghc
    run:
      name: Build package
      command: stack build --test --no-run-tests
      no_output_timeout: 30m

  # ghcjs steps
  - &init-remote-server
    run:
      name: Spin up remote build server
      command: echo init-remote-server
  - &upload-ghcjs-cache
    run:
      name: Upload GHCJS cache
      command: echo upload-ghcjs-cache
  - &remote-build-ghcjs
    run:
      name: Build with ghcjs remotely
      command: echo remote-build-ghcjs
      no_output_timeout: 30m
  - &download-ghcjs-artifacts
    run:
      name: Download GHCJS cache
      command: echo download-ghcjs-artifacts
  - &destroy-remote-server
    run:
      name: Terminate remote build server
      command: echo destroy-remote-server

  # test steps
  - &run-hlint
    run:
      name: Run hlint
      command: scripts/hlint.sh
  - &run-stylish-haskell
    run:
      name: Run stylish-haskell
      command: scripts/stylish-haskell.sh

jobs:
  prebuild:
    <<: *docker-linux
    steps:
      - checkout
      - *build-ghc-cache-key
      - *build-ghcjs-cache-key
      - persist_to_workspace:
          root: .
          paths:
            - ghc-cache-key.txt
            - ghcjs-cache-key.txt

  build-ghc:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      # dependencies
      - restore_cache:
          key: *ghc-cache-key
      - *install-system-deps
      - *install-stack-deps
      - save_cache:
          key: *ghc-cache-key
          paths:
            - ~/.stack
            - ~/.ghcjs
            - /usr/local/bin
            - /usr/local/lib/node
      # build
      - *run-build-ghc
      - persist_to_workspace:
          root: .
          paths:
              - .stack-work

  build-ghcjs:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: *ghcjs-cache-key
      - *init-remote-server
      - *upload-ghcjs-cache
      - *remote-build-ghcjs
      - *download-ghcjs-artifacts
      - *destroy-remote-server
      - save_cache:
          key: *ghcjs-cache-key
          paths:
            - ~/ghcjs-cache.tar.gz
      - store_artifacts:
          path: build.tar.gz

  lint:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: *ghc-cache-key
      - *run-hlint
      - *run-stylish-haskell

workflows:
  version: 2

  build_and_test:
    jobs:
      - prebuild
      - build-ghc:
          requires:
            - prebuild
      - build-ghcjs:
          requires:
            - prebuild
      - lint:
          requires:
            - build-ghc
