version: 2

aliases:
  # build environment
  - &docker-linux
    docker:
      - image: centos:7
    working_directory: /root/src

  # caches
  - &build-ghcjs-cache-key
    run:
      name: Build ghcjs cache key
      command: |
        FILES=(
          stack-ghcjs.yaml
          client/package.yaml
          scripts/install-system-deps.sh
          scripts/install-stack-deps.sh
        )
        cat "${FILES[@]}" > ghcjs-cache-key.txt
  - &ghcjs-cache-key
    v0-{{ checksum "ghcjs-cache-key.txt" }}
  - &ghcjs-cache-paths
    - ~/.stack-ghcjs
    - ~/.ghcjs
  - &build-cache-key
    run:
      name: Build cache key
      command: |
        FILES=(
          stack.yaml
          lib/package.yaml
          server/package.yaml
          scripts/install-system-deps.sh
          scripts/install-stack-deps.sh
        )
        cat "${FILES[@]}" > cache-key.txt
  - &cache-key
    v0-{{ checksum "cache-key.txt" }}
  - &cache-paths
    - ~/.stack
    - /usr/local/bin
    - /usr/local/lib/node

  # dependencies
  - &install-system-deps
    run:
      name: Build system dependencies
      command: scripts/install-system-deps.sh
  - &install-stack-deps
    run:
      name: Build stack dependencies
      command: scripts/install-stack-deps.sh

  # build steps
  - &run-build
    run:
      name: Build package
      command: ./build-all.sh --test --no-run-tests

  # test steps
  - &run-hlint
    run:
      name: Run hlint
      command: scripts/hlint.sh
  - &run-stylish-haskell
    run:
      name: Run stylish-haskell
      command: scripts/stylish-haskell.sh

jobs:
  prebuild:
    <<: *docker-linux
    steps:
      - checkout
      - *build-ghcjs-cache-key
      - *build-cache-key
      - persist_to_workspace:
          root: .
          paths:
            - ghcjs-cache-key.txt
            - cache-key.txt

  build:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      # dependencies
      - restore_cache:
          key: *ghcjs-cache-key
      - restore_cache:
          key: *cache-key
      - *install-system-deps
      - *install-stack-deps
      - save_cache:
          key: *ghcjs-cache-key
          paths: *ghcjs-cache-paths
      - save_cache:
          key: *cache-key
          paths: *cache-paths
      # build
      - *run-build
      - persist_to_workspace:
          root: .
          paths:
              - ghcjs/.stack-work

  hlint:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: *ghcjs-cache-key
      - restore_cache:
          key: *cache-key
      - *run-hlint

  stylish-haskell:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: *ghcjs-cache-key
      - restore_cache:
          key: *cache-key
      - *run-stylish-haskell

workflows:
  version: 2

  build_and_test:
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild
      - hlint:
          requires:
            - build
      - stylish-haskell:
          requires:
            - build
