_common/lib: !include "../hpack.yaml"
<<: *defaults

name: hive-server

dependencies:
  - base
  - bytestring
  - file-embed
  - http-media
  - path
  - servant
  - servant-server
  - wai

library:
  source-dirs:  src

executable:
  source-dirs:  exe
  main:         Main.hs
  dependencies:
    - hive-server
    - path-io
    - warp
